[package]
name = "card-collection-price-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"

[dev-dependencies]
mockall = "0.14.0"

[[bin]]
name = "ccpt"
path = "src/ccpt/main.rs"